server:
  port: 8081
hongru:
  path :
    #文件上传根目录 设置
    upload: /www/jeecgorm/upFiles
datasource:
  default: prod
  prod:
    username: jeecg-orm
    password: saGDFBYpybkPMprT
    databaseUrl: jdbc:mysql://127.0.0.1/jeecg-orm?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT%2B8&useSSL=false
    databaseDriver: com.mysql.cj.jdbc.Driver
